-- Problem 4-13 --

-- 1. 직급이 대리인 모든 사원들의 이름과 사원번호, 이들이 소속된 부서의 이름과 부서번호를 검색하라.
SELECT E.EMPNAME, E.EMPNO, D.DNAME, D.DEPTNO
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO = D.DEPTNO
AND E.TITLE = '대리';

-- 2. 각 프로젝트에 대하여 프로젝트의 이름, 관리자의 이름, 그 관리자가 소속된 부서의 이름을 검색하라.
SELECT P.PROJNAME, E.EMPNAME, D.DNAME
FROM EMPLOYEE E, DEPARTMENT D, PROJEMP P
WHERE P.PMANAGER = E.EMPNO
AND E.DNO = D.DEPTNO;

-- 3. 모든 사원들에 대하여 이름과 관리자의 이름을 검색하라.
SELECT E.EMPNAME, EE.EMPNAME
FROM EMPLOYEE E, EMPLOYEE EE
WHERE E.EMPNO = EE.MANAGER;

-- 4. 부서번호 2에 근무하면서 프로젝트 예산이 100,000,000원인 프로젝트를 관리하는 사원들의 이름과 급여를 검색하라.
SELECT E.EMPNAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, PROJEMP P
WHERE P.MANAGER = E.EMPNO
AND E.DNO = D.DEPTNO
AND D.DEPTNO = 2
AND P.BUDGET = 100,000,000;

-- 5. 서울에 위치한 부서에서 근무하는 사원들의 이름을 검색하라.
SELECT E.EMPNAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO = D.DEPTNO
AND D.LOCATION = '서울';

-- 6. 부서번호 1에 근무하는 사원들 중에서 적어도 부서번호 3에 근무하는 어떤 한 사원만큼 급여를 받는 사원들의 이름을 열거하라.
SELECT EMPNAME
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
AND DEPTNO = 1
AND E.SALARY >= ANY (SELECT DISTINCT SALARY FROM EMPLOYEE E, DEPARTMENT D
	WHERE E.DNO = D.DEPTNO AND D.DEPTNO = 3);

-- 7. 부서번호 3에 근무하지 않는 사원들 중에서 부서번호 3에 근무하는 모든 사원들의 급여보다 많은 급여를 받는 사원들의 이름을 검색하라.
SELECT EMPNAME FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
AND DEPTNO <> 3
AND SALARY > ALL (SELECT DISTINCT SALARY FROM EMPLOYEE E, DEPARTMENT D
	WHERE E.DNO = D.DEPTNO AND D.DEPTNO = 3);

-- 8. 사원들이 한 명도 소속되지 않은 부서들의 이름을 검색하라.
SELECT DNAME FROM DEPARTMENT
WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMPLOYEE, DEPARTMENT
	WHERE DNO = DEPTNO);