 N SELECT EMPNO, ENAME FROM EMP WHERE ENAME='SMITH';

SELECT * FROM EMP;

SELECT E.ENAME, E.EMPNO, E.DEPTNO FROM DEPT D INNER JOIN EMP E ON D.DEPTNO = E.DEPTNO;

SELECT 10 || 20 FROM DUAL;

SELECT '정답: 30' "10+20" FROM DUAL;

SELECT '정답: ' || (10+20) FROM DUAL;

SELECT ENAME || ' 의 사번은 ' || EMPNO || ' 입니다.' FROM EMP;

SELECT DISTINCT JOB FROM EMP;

SELECT ENAME 이름, EMPNO 사번, SAL 급여, SAL*12 연봉, SAL*12S+NVL(COMM,0) 총수입 FROM EMP;

SELECT * FROM EMP;

SELECT ENAME, EMPNO, SAL FROM EMP WHERE SAL=1250;

SELECT JOB, ENAME, EMPNO FROM EMP ORDER BY JOB DESC;

SELECT JOB, ENAME, EMPNO FROM EMP ORDER BY JOB DESC, ENAME ASC;

SELECT MGR, ENAME, EMPNO FROM EMP ORDER BY MGR ASC NULLS FIRST;

SELECT ENAME 이름, SAL 급여, SAL*12 연봉 FROM EMP ORDER BY 연봉 DESC;

SELECT ENAME 이름, SAL 급여, SAL*12 연봉, SAL*12+NVL(COMM,0) 총수입 FROM EMP ORDER BY 총수입 DESC;

SELECT ENAME, EMPNO FROM EMP WHERE ENAME='FORD';

SELECT ENAME, EMPNO, JOB FROM EMP WHERE JOB='CLERK';

SELECT ENAME, EMPNO, SAL FROM EMP WHERE SAL>=1350;

SELECT ENAME 이름, EMPNO 사번, SAL*12+NVL(COMM,0) 총수입 FROM EMP WHERE SAL*12+NVL(COMM,0)>=30000 ORDER BY 총수입 DESC;

SELECT ENAME, EMPNO, HIREDATE FROM EMP WHERE HIREDATE>='19820101';

SELECT ENAME, EMPNO, HIREDATE FROM EMP WHERE HIREDATE>='19820101';

SELECT ENAME, EMPNO, COMM FROM EMP WHERE COMM IS NOT NULL AND COMM<>0;

SELECT ENAME, EMPNO, COMM FROM EMP WHERE COMM IS NULL OR COMM=0;

SELECT ENAME, EMPNO, JOB, DEPTNO FROM EMP WHERE DEPTNO=10;

SELECT ENAME, EMPNO, MGR FROM EMP WHERE MGR=7566;

SELECT ENAME, EMPNO, SAL FROM EMP WHERE SAL>=1500 AND SAL<=2990;

SELECT ENAME, EMPNO, JOB, SAL FROM EMP WHERE JOB='CLERK' AND SAL<1000;

SELECT ENAME, EMPNO, DEPTNO FROM EMP WHERE DEPTNO<>10;

SELECT ENAME, EMPNO, JOB, SAL, HIREDATE, DEPTNO FROM EMP WHERE JOB='CLERK' AND SAL>=1000 AND HIREDATE>='19820101' AND DEPTNO<>20;

SELECT ENAME, SAL FROM EMP WHERE SAL IN (1300,1100);

SELECT ENAME, SAL FROM EMP WHERE SAL IN (1300,1600) AND DEPTNO=20;

SELECT ENAME, EMPNO, JOB, DEPTNO FROM EMP WHERE DEPTNO=20 OR JOB='CLERK';

SELECT ENAME, EMPNO FROM EMP WHERE ENAME LIKE 'A%';

SELECT ENAME, EMPNO FROM EMP WHERE ENAME LIKE '%E_';

SELECT ENAME, SAL FROM EMP WHERE SAL BETWEEN 1250 AND 1600;

SELECT DNAME, ENAME, DEPTNO, EMPNO FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE DNAME='SALES';

SELECT ENAME, EMPNO, DNAME, LOC FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE JOB='CLERK';

SELECT DNAME, LOC, DEPTNO, ENAME, EMPNO FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE LOC='DALLAS';

SELECT ENAME 이름, DNAME 부서명, SAL*12+NVL(COMM,0) 총수입 FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL*12+NVL(COMM,0)>20000;

SELECT ENAME, DNAME, SAL FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL BETWEEN 1500 AND 2500;

SELECT GRADE FROM SALGRADE WHERE (SELECT SAL FROM EMP WHERE ENAME='SMITH') BETWEEN LOSAL AND HISAL;

SELECT ENAME, JOB, SAL, GRADE FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE JOB='SALESMAN' AND SAL BETWEEN LOSAL AND HISAL;

SELECT ENAME, DNAME, LOC, SAL, GRADE FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE LOC='CHICAGO' AND SAL BETWEEN LOSAL AND HISAL;

SELECT ENAME, DNAME, GRADE FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL>2000;

SELECT DISTINCT M.ENAME, M.SAL, GRADE, D.DNAME FROM SALGRADE, EMP E INNER JOIN EMP M ON E.MGR=M.EMPNO INNER JOIN DEPT D 
ON M.DEPTNO=D.DEPTNO WHERE M.SAL BETWEEN LOSAL AND HISAL;

SELECT ENAME, DEPTNO, EMPNO FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE DNAME=(SELECT DNAME FROM EMP INNER JOIN DEPT 
USING (DEPTNO) WHERE ENAME='SMITH');

SELECT ENAME, EMPNO, DEPTNO FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');

SELECT DISTINCT E.EMPNO FROM EMP E, EMP M WHERE E.EMPNO=M.MGR;

SELECT DISTINCT EMPNO FROM EMP;

SELECT ENAME, EMPNO, SAL, GRADE, DNAME FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL BETWEEN LOSAL AND HISAL; 

SELECT E.ENAME 이름, E.SAL 급여, GRADE 급여등급, M.ENAME 상관이름 FROM SALGRADE, EMP E INNER JOIN EMP M ON E.MGR=M.EMPNO
WHERE (E.SAL BETWEEN LOSAL AND HISAL) AND GRADE=1;

SELECT E.ENAME, E.EMPNO, GRADE, E.DEPTNO, M.ENAME, D.DNAME FROM SALGRADE, EMP E INNER JOIN EMP M ON E.MGR=M.EMPNO
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO
WHERE (E.SAL BETWEEN LOSAL AND HISAL) AND E.ENAME='SMITH';

SELECT D.DNAME SALES부서명, E.ENAME 직원이름, E.SAL*12+NVL(E.COMM,0) 직원1년총수입, MD.DNAME 상관부서명, M.ENAME 상관이름,
M.SAL*12+NVL(M.COMM,0) 상관1년총수입 FROM EMP E INNER JOIN EMP M ON E.MGR=M.EMPNO
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO INNER JOIN DEPT MD ON M.DEPTNO=MD.DEPTNO WHERE D.DNAME='SALES';

CREATE TABLE EMP2(ENAME VARCHAR2(10), DEPTNO NUMBER(2));
CREATE TABLE DEPT2(DNAME VARCHAR2(10), DEPTNO NUMBER(2));

INSERT INTO EMP2 VALUES('JANE',10);
INSERT INTO EMP2 VALUES('TOM',20);
INSERT INTO EMP2 VALUES('ALICE',10);
INSERT INTO EMP2 VALUES('JOHN',NULL);

INSERT INTO DEPT2 VALUES('HR',10);
INSERT INTO DEPT2 VALUES('IT',20);
INSERT INTO DEPT2 VALUES('TFT',NULL);

SELECT DNAME, ENAME, DEPTNO FROM EMP2 INNER JOIN DEPT2 USING (DEPTNO);

SELECT DNAME, ENAME, DEPTNO FROM DEPT2 LEFT OUTER JOIN EMP2 USING (DEPTNO);

SELECT DNAME, ENAME, DEPTNO FROM DEPT2 RIGHT OUTER JOIN EMP2 USING (DEPTNO);

SELECT DNAME, ENAME, DEPTNO FROM DEPT2 FULL OUTER JOIN EMP2 USING (DEPTNO);

SELECT DNAME, ENAME, DEPTNO FROM DEPT2 JOIN EMP2 USING (DEPTNO);

SELECT 'WELCOME TO ORACLE' FROM DUAL;

SELECT UPPER('selct') FROM DUAL;

SELECT LOWER('SELECT') FROM DUAL;

SELECT INITCAP('sELECT') FROM DUAL;

SELECT CONCAT('WIZARD',' KLAUS') FROM DUAL;

SELECT SUBSTR('WIZARD KLAUS',1,6) FROM DUAL;

SELECT INSTR('WIZARD KLAUS','K') FROM DUAL;

SELECT LPAD('KLAUS',12,'WIZARD ') FROM DUAL;

SELECT RPAD('WIZARD',12,' KLAUS') FROM DUAL;

SELECT ROUND(4.5) FROM DUAL;

SELECT TRUNC(3.3) FROM DUAL;

SELECT MOD(30,12) FROM DUAL;

SELECT POWER(30,2) FROM DUAL;

SELECT SQRT(64) FROM DUAL;

SELECT CEIL(30.16) FROM DUAL;

SELECT FLOOR(30.16) FROM DUAL;

SELECT DNAME 부서이름, ENAME 직원이름, CONCAT(TRUNC(SAL,-2),'원') 급여, GRADE 급여등급, CONCAT('$',TRUNC(((SAL*12+NVL(COMM,0))*1.15),-2)) "15증가분"
FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE TRUNC(SAL,-2) BETWEEN LOSAL AND HISAL;

SELECT LTRIM('WIZARD KLAUS','WIZARD ') FROM DUAL;

SELECT RTRIM('WIZARD KLAUS',' KLAUS') FROM DUAL;

SELECT TRIM('*' FROM '***WIZARDKLAUS***') FROM DUAL;

SELECT TRIM(LEADING '*' FROM '***WIZARDKLAUS***') FROM DUAL;

SELECT TRIM(TRAILING '*' FROM '***WIZARDKLAUS***') FROM DUAL;

SELECT LENGTH('WIZARD KLAUS') FROM DUAL;

SELECT LENGTHB('위저드 클라우스') FROM DUAL;

SELECT 'WIZARD KLAUS', TRANSLATE('WIZARD KLAUS','KLA','***'), REPLACE('WIZARD KLAUS','KLA','***') FROM DUAL;

SELECT REPLACE('***WIZARD***KLAUS***','*','') FROM DUAL;

SELECT ENAME, LPAD(ENAME,7,' ') 왼쪽정렬, RPAD(ENAME,7,' ') 오른쪽정렬 FROM EMP;

SELECT ENAME, CONCAT('$',LPAD(SAL,10,' ')) 달러표시 FROM EMP;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD:HH24:MT:SS';

SELECT SYSDATE -1 어제, SYSDATE 오늘, SYSDATE +1 내일 FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY:MM:DD:HH:MI:SS:PM') 년월일시분초 FROM DUAL;

SELECT ENAME, CONCAT(TO_DATE(TO_CHAR(SYSDATE,'YY/MM/DD'))-HIREDATE,'일') 근무일수 FROM EMP WHERE ENAME='SMITH';

SELECT ENAME, CONCAT(TO_DATE(TO_CHAR(SYSDATE,'YY/MM/DD'))-HIREDATE,'일') 근무일수 FROM EMP
WHERE TO_DATE(TO_CHAR(SYSDATE,'YY/MM/DD'))-HIREDATE>13200;

SELECT ENAME, MONTHS_BETWEEN(SYSDATE,HIREDATE) FROM EMP;

SELECT ADD_MONTHS(SYSDATE,15) FROM DUAL;

SELECT SYSDATE, ROUND(SYSDATE,'YY'), ROUND(SYSDATE,'MM'), ROUND(SYSDATE,'DD') FROM DUAL;

SELECT JOB, AVG(SAL) FROM EMP WHERE MGR IS NOT NULL GROUP BY JOB HAVING AVG(SAL)<1500;

SELECT DNAME, COUNT(EMPNO) FROM EMP INNER JOIN DEPT USING (DEPTNO) GROUP BY DNAME HAVING COUNT(EMPNO)>=4 ORDER BY COUNT(EMPNO) DESC;

SELECT JOB, AVG(SAL) FROM EMP WHERE HIREDATE>TO_DATE(19810429,'YYYY/MM/DD') GROUP BY JOB HAVING AVG(SAL)>2000;

SELECT GRADE, COUNT(EMPNO) FROM SALGRADE, EMP WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE<=3 GROUP BY GRADE;

SELECT ENAME, SAL FROM EMP WHERE SAL=(SELECT SAL FROM EMP WHERE ENAME='MARTIN');

SELECT ENAME, EMPNO, SAL FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);

SELECT ENAME, SAL, GRADE, DNAME FROM SALGRADE, EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL>(SELECT AVG(SAL) FROM EMP INNER JOIN DEPT USING (DEPTNO)
WHERE DNAME='SALES' GROUP BY DNAME) AND SAL BETWEEN LOSAL AND HISAL;

SELECT E.ENAME, E.JOB, D.DNAME, E.SAL, GRADE, M.ENAME, DM.DNAME FROM SALGRADE, EMP E INNER JOIN EMP M ON E.MGR=M.EMPNO 
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO INNER JOIN DEPT DM ON M.DEPTNO=DM.DEPTNO
WHERE E.SAL<(SELECT AVG(SAL) FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='MARTIN') GROUP BY JOB)
AND E.SAL BETWEEN LOSAL AND HISAL;

SELECT ENAME, EMPNO, DNAME, LOC FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE DNAME=(SELECT DNAME FROM EMP INNER JOIN DEPT USING (DEPTNO)
WHERE ENAME='SMITH');

SELECT ENAME, EMPNO, DNAME, LOC FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE DNAME='RESEARCH' AND LOC='DALLAS';

SELECT ENAME, EMPNO, DNAME, LOC FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE (DNAME,LOC) IN (('RESEARCH','DALLAS'),('SALES','CHICAGO'));

SELECT ENAME, SAL, JOB FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE SAL>ALL(SELECT SAL FROM EMP WHERE JOB='SALESMAN');

INSERT INTO EMP2 (SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO=20);

CREATE TABLE EMP3 AS SELECT ENAME, EMPNO, JOB, DEPTNO FROM EMP;

CREATE TABLE DEPT3 AS SELECT * FROM DEPT;

INSERT INTO DEPT3(DEPTNO, DNAME, LOC) VALUES (50,'IT','SEOUL');

SELECT * FROM DEPT3;

INSERT INTO DEPT3 VALUES (60,'MKT','BUSAN');

UPDATE DEPT3 SET LOC='JEJU' WHERE DEPTNO=50;

UPDATE DEPT3 SET LOC='SEOUL' WHERE DEPTNO=60;

DELETE FROM EMP2 WHERE DEPTNO IS NULL;

CREATE TABLE DEPT4 AS SELECT * FROM DEPT3;

DELETE FROM DEPT3 WHERE DEPTNO IN (50,60);

DELETE FROM DEPT4 WHERE DEPTNO IN (20,40);

SELECT * FROM DEPT3 UNION SELECT * FROM DEPT4;

SELECT * FROM DEPT3 UNION ALL SELECT * FROM DEPT4;

SELECT * FROM DEPT3 INTERSECT SELECT * FROM DEPT4;

SELECT * FROM DEPT3 MINUS SELECT * FROM DEPT4;

INSERT INTO DEPT3 VALUES (50,'IT','SEOUL');

UPDATE DEPT3 SET LOC='JEJU' WHERE DEPTNO=30;

SELECT ENAME, DNAME, CASE WHEN DNAME='SALES' THEN '세일즈' WHEN DNAME='RESEARCH' THEN '리서치' WHEN DNAME='ACCOUNTING' THEN '회계'
WHEN DNAME='OPERATIONS' THEN '유지보수' ELSE '몰라' END CASE문 FROM EMP INNER JOIN DEPT USING (DEPTNO);

INSERT INTO DEPT3 VALUES (60,'IT1','A');
SAVEPOINT A;

INSERT INTO DEPT3 VALUES (70,'IT2','B');
SAVEPOINT B;

INSERT INTO DEPT3 VALUES (70,'IT2','B');
SAVEPOINT C;

ROLLBACK TO B;
SELECT * FROM DEPT3;

CREATE TABLE TEST(NAME VARCHAR(10) PRIMARY KEY CHECK(NAME>3));

DROP TABLE CUSTTBL;
CREATE TABLE CUSTTBL (CNO NUMBER(2) CONSTRAINT CUSTTBL_PK PRIMARY KEY, CNAME VARCHAR2(20) NOT NULL UNIQUE, 
GENDER CHAR(1) NOT NULL CHECK(GENDER IN('남','여')), AGE NUMBER(3) NOT NULL CHECK(AGE BETWEEN 1 AND 99), JOB VARCHAR2(20), ADDR VARCHAR2(10), 
MOB1 CHAR(3) CHECK(MOB1 IN('010','016','019')), MOB2 CHAR(8), CDATE DATE DEFAULT SYSDATE);

ALTER TABLE CUSTTBL DROP CONSTRAINT SYS_C0010834;

ALTER TABLE CUSTTBL ADD CONSTRAINT CHECK_GENDER CHECK (GENDER IN('M','F'));

CREATE TABLE BUYTBL (BNP NUMBER(2) CONSTRAINT BUYTBL PRIMARY KEY, BNAME VARCHAR2(20), PRICE NUMBER(3), AMOUNT NUMBER(2), 
CNO NUMBER(2) CONSTRAINT CUSTTBL_FK REFERENCES CUSTTBL(CNO));

INSERT INTO CUSTTBL VALUES (1,'TOM','M',32,'IT','JEJU','010','11111111',DEFAULT);

INSERT INTO BUYTBL VALUES (1,'NOTEBOOK',100,1,1);

SELECT * FROM BUYTBL;

SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'CUST%';

ALTER TABLE BUYTBL ADD CMP VARCHAR2(20);

ALTER TABLE BUYTBL DROP COLUMN CMP;

CREATE TABLE EMP4 AS SELECT * FROM EMP;

CREATE TABLE T1 (TNO NUMBER(2), TXT VARCHAR(10));

CREATE SEQUENCE T1_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO T1 VALUES (T1_SEQ.NEXTVAL, 'AAA');

INSERT INTO T1 VALUES (T1_SEQ.NEXTVAL, 'BBB');

SELECT * FROM T1;

CREATE UNIQUE INDEX IDX_EMP4_ENAME ON EMP4(ENAME);

SELECT * FROM EMP4;

